A notebook to test the ways to merge data with pandas framework

In [1]:
import pandas as pd

In [2]:
hwrf = "testdata/Final_Attributes_2022122606HWRF+20221225DFO+20221225VIIRSUpdated.csv"
popcount = "processing/Final_Attributes_2022122606HWRF+20221225DFO+20221225VIIRSPopCount.csv"
allpopcount = "popcount_2020.csv"

In [3]:
hwrf_df = pd.read_csv(hwrf)
pop_df = pd.read_csv(popcount)
allpop_df = pd.read_csv(allpopcount)

In [4]:
# drop totalpop column
pop_df = pop_df.drop(['totalpop'], axis=1)

In [5]:
joindpop_df = allpop_df.set_index('pfaf_id').join(pop_df.set_index('pfaf_id'))

In [6]:
joindpop_df.head()

         totalpop  viirs_impactpop  viirs_impactpop_percent
pfaf_id
111011     326082              NaN                      NaN
111012       2390              NaN                      NaN
111013       8152              NaN                      NaN
111014         72              NaN                      NaN
111015     292552              NaN                      NaN

In [7]:
merged_df = hwrf_df.set_index('pfaf_id').join(joindpop_df)

In [8]:
merged_df.head()

,FID,area_km2,ISO,Admin0,Admin1,rfr_score,cfr_score,Resilience_Index,NormalizedLackofResilience,FID_x,...,VIIRS_area_1day_score,VIIRS_percarea_1day_score,VIIRS_area_5day_score,VIIRS_percarea_5day_score,VIIRSTotal_Score,Severity,Alert,totalpop,viirs_impactpop,viirs_impactpop_percent
pfaf_id,,,,,,,,,,,,,,,,,,,,,
111011,0.0,1894.935871,EGY,Egypt,As Suways,4.180674,0.000000,0.55,0.63,0.0,...,0.014766,0.077922,0.378984,1.999985,2.471657,0.029274,Information,326082,NaN,NaN
111013,2.0,895.121761,EGY,Egypt,As Suways,4.008112,0.000000,0.55,0.63,2.0,...,0.084375,0.942609,1.264922,14.131283,16.423189,0.425088,Advisory,8152,NaN,NaN
111015,4.0,16672.323330,EGY,Egypt,Al Bahr al Ahmar,4.159506,1.332959,0.55,0.63,4.0,...,0.923906,0.554156,6.875859,4.124116,12.478037,0.382853,Advisory,292552,NaN,NaN
111016,5.0,1836.632450,EGY,Egypt,Al Bahr al Ahmar,4.105107,0.000000,0.55,0.63,5.0,...,NaN,NaN,NaN,NaN,NaN,0.032081,Information,0,NaN,NaN
111017,6.0,8665.540548,EGY,Egypt,Al Bahr al Ahmar,4.007958,0.000000,0.55,0.63,6.0,...,0.103359,0.119276,1.742344,2.010658,3.975637,0.053966,Information,50483,NaN,NaN

In [9]:
# need to move column position
popcols = joindpop_df.columns.tolist()
popcols

['totalpop', 'viirs_impactpop', 'viirs_impactpop_percent']

In [10]:
hwrfcols = hwrf_df.set_index('pfaf_id').columns.tolist()
hwrfcols

['FID',
 'area_km2',
 'ISO',
 'Admin0',
 'Admin1',
 'rfr_score',
 'cfr_score',
 'Resilience_Index',
 ' NormalizedLackofResilience ',
 'FID_x',
 'FID_y',
 'Alert_level',
 'Days_until_peak',
 'GloFAS_2yr',
 'GloFAS_5yr',
 'GloFAS_20yr',
 'Alert_Score',
 'PeakArrivalScore',
 'TwoYScore',
 'FiveYScore',
 'TwtyYScore',
 'Sum_Score_x',
 'GFMS_TotalArea_km',
 'GFMS_perc_Area',
 'GFMS_MeanDepth',
 'GFMS_MaxDepth',
 'GFMS_Duration',
 'GFMS_area_score',
 'GFMS_perc_area_score',
 'MeanD_Score',
 'MaxD_Score',
 'Duration_Score',
 'Sum_Score_y',
 'MOM_Score',
 'Hazard_Score',
 'Scaled_Riverine_Risk',
 'Scaled_Coastal_Risk',
 'Flag',
 '1-Day_TotalArea_km2',
 '1-Day_perc_Area',
 '1-Day_CS_TotalArea_km2',
 '1-Day_CS_perc_Area',
 '2-Day_TotalArea_km2',
 '2-Day_perc_Area',
 '3-Day_TotalArea_km2',
 '3-Day_perc_Area',
 'DFO_area_1day_score',
 'DFO_percarea_1day_score',
 'DFO_area_2day_score',
 'DFO_percarea_2day_score',
 'DFO_area_3day_score',
 'DFO_percarea_3day_score',
 'DFOTotal_Score',
 'onedayFlood_Area_km',
 'onedayperc_Area',
 'fivedayFlood_Area_km',
 'fivedayperc_Area',
 'VIIRS_area_1day_score',
 'VIIRS_percarea_1day_score',
 'VIIRS_area_5day_score',
 'VIIRS_percarea_5day_score',
 'VIIRSTotal_Score',
 'Severity',
 'Alert']

In [11]:
viirspos=hwrfcols.index("VIIRSTotal_Score")

In [12]:
newcols = hwrfcols[:viirspos+1] + popcols + hwrfcols[viirspos+1:]
newcols

['FID',
 'area_km2',
 'ISO',
 'Admin0',
 'Admin1',
 'rfr_score',
 'cfr_score',
 'Resilience_Index',
 ' NormalizedLackofResilience ',
 'FID_x',
 'FID_y',
 'Alert_level',
 'Days_until_peak',
 'GloFAS_2yr',
 'GloFAS_5yr',
 'GloFAS_20yr',
 'Alert_Score',
 'PeakArrivalScore',
 'TwoYScore',
 'FiveYScore',
 'TwtyYScore',
 'Sum_Score_x',
 'GFMS_TotalArea_km',
 'GFMS_perc_Area',
 'GFMS_MeanDepth',
 'GFMS_MaxDepth',
 'GFMS_Duration',
 'GFMS_area_score',
 'GFMS_perc_area_score',
 'MeanD_Score',
 'MaxD_Score',
 'Duration_Score',
 'Sum_Score_y',
 'MOM_Score',
 'Hazard_Score',
 'Scaled_Riverine_Risk',
 'Scaled_Coastal_Risk',
 'Flag',
 '1-Day_TotalArea_km2',
 '1-Day_perc_Area',
 '1-Day_CS_TotalArea_km2',
 '1-Day_CS_perc_Area',
 '2-Day_TotalArea_km2',
 '2-Day_perc_Area',
 '3-Day_TotalArea_km2',
 '3-Day_perc_Area',
 'DFO_area_1day_score',
 'DFO_percarea_1day_score',
 'DFO_area_2day_score',
 'DFO_percarea_2day_score',
 'DFO_area_3day_score',
 'DFO_percarea_3day_score',
 'DFOTotal_Score',
 'onedayFlood_Area_km',
 'onedayperc_Area',
 'fivedayFlood_Area_km',
 'fivedayperc_Area',
 'VIIRS_area_1day_score',
 'VIIRS_percarea_1day_score',
 'VIIRS_area_5day_score',
 'VIIRS_percarea_5day_score',
 'VIIRSTotal_Score',
 'totalpop',
 'viirs_impactpop',
 'viirs_impactpop_percent',
 'Severity',
 'Alert']

In [13]:
len(newcols)

67

In [14]:
len(merged_df.columns.tolist())

67

In [15]:
reordered_df = merged_df[newcols]

In [16]:
reordered_df.head()

,FID,area_km2,ISO,Admin0,Admin1,rfr_score,cfr_score,Resilience_Index,NormalizedLackofResilience,FID_x,...,VIIRS_area_1day_score,VIIRS_percarea_1day_score,VIIRS_area_5day_score,VIIRS_percarea_5day_score,VIIRSTotal_Score,totalpop,viirs_impactpop,viirs_impactpop_percent,Severity,Alert
pfaf_id,,,,,,,,,,,,,,,,,,,,,
111011,0.0,1894.935871,EGY,Egypt,As Suways,4.180674,0.000000,0.55,0.63,0.0,...,0.014766,0.077922,0.378984,1.999985,2.471657,326082,NaN,NaN,0.029274,Information
111013,2.0,895.121761,EGY,Egypt,As Suways,4.008112,0.000000,0.55,0.63,2.0,...,0.084375,0.942609,1.264922,14.131283,16.423189,8152,NaN,NaN,0.425088,Advisory
111015,4.0,16672.323330,EGY,Egypt,Al Bahr al Ahmar,4.159506,1.332959,0.55,0.63,4.0,...,0.923906,0.554156,6.875859,4.124116,12.478037,292552,NaN,NaN,0.382853,Advisory
111016,5.0,1836.632450,EGY,Egypt,Al Bahr al Ahmar,4.105107,0.000000,0.55,0.63,5.0,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.032081,Information
111017,6.0,8665.540548,EGY,Egypt,Al Bahr al Ahmar,4.007958,0.000000,0.55,0.63,6.0,...,0.103359,0.119276,1.742344,2.010658,3.975637,50483,NaN,NaN,0.053966,Information

In [17]:
reordered_df.to_csv("megredhwrf.csv")

In [20]:
print(joindpop_df.shape[0])
print(hwrf_df.shape[0])
print(reordered_df.shape[0])

16396
10310
10310